In [2]:
#1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.
n1 = [10,20,30,40,50]
print("Original Numbers:",n1)

n1.append(60)       #Adding 60 into list
print("After appending (60) :",n1)

n1.extend([70, 80])  # Add multiple elements
print("After extend:", n1)

n1.insert(2, 25)  # Insert element at index 2
print("After insert:", n1)

n1.remove(40)  # Remove first occurrence of value 40
print("After remove:", n1)

popped = n1.pop()  # Remove and return the last element
print("After pop:", n1, " | Popped element:", popped)

index_30 = n1.index(30)  # Get index of value 30
print("Index of 30:", index_30)

count_20 = n1.count(20)  # Count occurrences of 20
print("Count of 20:", count_20)

n1.sort()  # Sort ascending
print("After sort:", n1)

n1.reverse()  # Reverse the list
print("After reverse:", n1)

n1.clear()  # Remove all elements
print("After clear:", n1)

Original Numbers: [10, 20, 30, 40, 50]
After appending (60) : [10, 20, 30, 40, 50, 60]
After extend: [10, 20, 30, 40, 50, 60, 70, 80]
After insert: [10, 20, 25, 30, 40, 50, 60, 70, 80]
After remove: [10, 20, 25, 30, 50, 60, 70, 80]
After pop: [10, 20, 25, 30, 50, 60, 70]  | Popped element: 80
Index of 30: 3
Count of 20: 1
After sort: [10, 20, 25, 30, 50, 60, 70]
After reverse: [70, 60, 50, 30, 25, 20, 10]
After clear: []


In [5]:
#2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.
s1 = ("Abhi" , "Mugdha" , "Manisha")
print("Original Tuple :", s1)

try:
    s1[1] = "Priya"
except TypeError as e:
    print("Error:", e)
    print("Explanation: Tuples are immutable, so their elements cannot be changed after creation.")


Original Tuple : ('Abhi', 'Mugdha', 'Manisha')
Error: 'tuple' object does not support item assignment
Explanation: Tuples are immutable, so their elements cannot be changed after creation.


In [6]:
#3.	Create a set of integers with some duplicate values. Print the set and explain the output.
n2 = {1, 2, 3, 2, 4, 3, 5}
print("\nSet with duplicates removed:", n2)
print("Explanation: Sets automatically remove duplicate values and store only unique elements.")


Set with duplicates removed: {1, 2, 3, 4, 5}
Explanation: Sets automatically remove duplicate values and store only unique elements.


In [8]:
#4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.
P1 = {"name": "Abhi", "age": 25, "city": "Pune"}
P1["age"] = 26  # Updating age
P1["email"] = "abhi@example.com"  # Add new key-value pair
print("\nUpdated dictionary:", P1)


Updated dictionary: {'name': 'Abhi', 'age': 26, 'city': 'Pune', 'email': 'abhi@example.com'}


In [9]:
#Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.
age = 17
if age >= 18:
    print("\nEligible to vote")
else:
    print("Not eligible to vote (must be 18 or older)")

Not eligible to vote (must be 18 or older)


In [11]:
#6.	Given a 'marks' variable, print the grade:
#- 90 and above: 'A'
#- 75–89: 'B'
#- 50–74: 'C'
#- Below 50: 'Fail'
marks = 93
if marks >= 90:
    print("\nGrade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Grade: Fail")


Grade: A


In [16]:
#7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.
number = 1
if number > 0:
    if number % 2 == 0:
        print("\nThe number is positive and even.")
    else:
        print("The number is positive but odd.")
elif number == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

The number is positive but odd.


In [2]:
#Section B: Numpy 

#8

import numpy as np
scalar = np.array(5)
array_1d = np.array([1,2,3,4,5])
array_2d = np.array([[10,20,30] , [40,50,60]])

print("Scalar:\n", scalar)
print("1D array:\n", array_1d)
print("2D array:\n", array_2d)

Scalar:
 5
1D array:
 [1 2 3 4 5]
2D array:
 [[10 20 30]
 [40 50 60]]


In [5]:
#9
import numpy as np
random_array = np.random.randint(0,100,size=(4,4))
print("4X4 Random Array:",random_array)

4X4 Random Array: [[80 97 60 20]
 [77 48 73 27]
 [48 83 83 36]
 [30 35 99 10]]


In [7]:
# 10
import numpy as np
import pandas as pd
array_2d_for_df=([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
df=pd.DataFrame(array_2d_for_df,columns=['A','B','C'])
print("DataFrame:\n", df)

DataFrame:
    A  B  C
0  1  2  3
1  4  5  6
2  7  8  9


In [16]:
import pandas as pd
import numpy as np

# 11. Creating a small DataFrame manually
data = {
    'Name': ['Amit', 'Priya', 'Rahul', 'Sneha', 'Vikas', 'Amit', 'Kiran', 'Meena', 'Raj', 'Tina'],
    'Age': [25, 30, 28, 22, 35, 25, 29, 24, 31, 27],
    'City': ['Pune', 'Mumbai', 'Delhi', 'Chennai', 'Pune', 'Pune', 'Delhi', 'Mumbai', 'Chennai', 'Pune'],
    'Salary': [50000, 60000, 55000, np.nan, 65000, 50000, 58000, 62000, 64000, np.nan]
}

df = pd.DataFrame(data)
print("Original DataFrame:\n", df)

# Display info and statistics
print("\n--- DataFrame Info ---")
print(df.info())

print("\n--- Statistical Summary ---")
print(df.describe())

# Select 'Name' and 'City' columns
print("\n--- Selected Columns (Name, City) ---")
print(df[['Name', 'City']])

# Drop 'City' column
df_dropped = df.drop('City', axis=1)
print("\n--- DataFrame after dropping 'City' ---")
print(df_dropped)

# Fill missing values in 'Salary' with mean
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
print("\n--- DataFrame after filling missing Salary values ---")
print(df)

# Remove duplicate rows
df_no_duplicates = df.drop_duplicates()
print("\n--- DataFrame after removing duplicates ---")
print(df_no_duplicates)

Original DataFrame:
     Name  Age     City   Salary
0   Amit   25     Pune  50000.0
1  Priya   30   Mumbai  60000.0
2  Rahul   28    Delhi  55000.0
3  Sneha   22  Chennai      NaN
4  Vikas   35     Pune  65000.0
5   Amit   25     Pune  50000.0
6  Kiran   29    Delhi  58000.0
7  Meena   24   Mumbai  62000.0
8    Raj   31  Chennai  64000.0
9   Tina   27     Pune      NaN

--- DataFrame Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes
None

--- Statistical Summary ---
             Age        Salary
count  10.000000      8.000000
mean   27.600000  58000.000000
std     3.835507   5879.747322
min    22.000000  50000.000000
25%    25.000000  53750.